name: "Interact"

on: [push, pull_request]

jobs:
  interact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run script
        env:
          ACCOUNT_USER: ${{ secrets.ACCOUNT_USER }}
          ACCOUNT_TOKEN: ${{ secrets.ACCOUNT_TOKEN }}
        run: ls -la && ./script.sh

        